// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_cosmo_we_are_friends = "CgkIxtqO55YJEAIQCA"; // <GPGSID>
        public const string leaderboard_dungeonexit = "CgkIxtqO55YJEAIQBQ"; // <GPGSID>
        public const string achievement_chrono_we_are_friends = "CgkIxtqO55YJEAIQCQ"; // <GPGSID>
        public const string achievement_escape_master = "CgkIxtqO55YJEAIQDw"; // <GPGSID>
        public const string achievement_escape_experienced = "CgkIxtqO55YJEAIQDQ"; // <GPGSID>
        public const string achievement_misty_we_are_friends = "CgkIxtqO55YJEAIQCg"; // <GPGSID>
        public const string achievement_leo_we_are_friends = "CgkIxtqO55YJEAIQBw"; // <GPGSID>
        public const string leaderboard_dungeonexitstreak = "CgkIxtqO55YJEAIQBA"; // <GPGSID>
        public const string leaderboard_gold = "CgkIxtqO55YJEAIQAw"; // <GPGSID>
        public const string achievement_escape_intermediate = "CgkIxtqO55YJEAIQDA"; // <GPGSID>
        public const string achievement_escape_god = "CgkIxtqO55YJEAIQEA"; // <GPGSID>
        public const string achievement_bambi_we_are_friends = "CgkIxtqO55YJEAIQBg"; // <GPGSID>
        public const string achievement_escape_begginer = "CgkIxtqO55YJEAIQCw"; // <GPGSID>
        public const string achievement_escape_proficient = "CgkIxtqO55YJEAIQDg"; // <GPGSID>

}

